"""SQLAlchemy database models for the FX Option platform."""
from __future__ import annotations

from datetime import datetime
from typing import Optional

from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from services.database.session import Base


class User(Base):
    """User account for authentication and authorization."""

    __tablename__ = "users"

    id = Column(String(36), primary_key=True)
    email = Column(String(255), unique=True, nullable=False, index=True)
    username = Column(String(100), unique=True, nullable=False, index=True)
    hashed_password = Column(String(255), nullable=False)
    full_name = Column(String(255))
    is_active = Column(Boolean, default=True, nullable=False)
    is_superuser = Column(Boolean, default=False, nullable=False)
    role = Column(String(50), nullable=False, default="client")  # client, operator, admin
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    last_login = Column(DateTime(timezone=True))

    # Relationships
    exposures = relationship("Exposure", back_populates="user", cascade="all, delete-orphan")
    quotes = relationship("Quote", back_populates="user", cascade="all, delete-orphan")
    orders = relationship("Order", back_populates="user", cascade="all, delete-orphan")


class Exposure(Base):
    """Foreign exchange exposure from accounting system."""

    __tablename__ = "exposures"

    id = Column(String(36), primary_key=True)
    user_id = Column(String(36), ForeignKey("users.id"), nullable=False, index=True)
    source = Column(String(50), nullable=False)  # qbo, siigo, manual
    external_id = Column(String(255), index=True)  # invoice ID from external system
    currency_pair = Column(String(10), nullable=False, index=True)  # USDMXN, EURUSD
    notional = Column(Numeric(18, 2), nullable=False)
    currency = Column(String(3), nullable=False)  # MXN, EUR
    due_date = Column(DateTime(timezone=True), nullable=False, index=True)
    counterparty = Column(String(255))
    status = Column(String(50), default="active", nullable=False)  # active, hedged, expired, cancelled
    extra_data = Column(JSON)  # Additional data from source system
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationships
    user = relationship("User", back_populates="exposures")
    quotes = relationship("Quote", back_populates="exposure", cascade="all, delete-orphan")

    __table_args__ = (
        Index("ix_exposures_user_status", "user_id", "status"),
        Index("ix_exposures_currency_due", "currency_pair", "due_date"),
    )


class Quote(Base):
    """Binding option quote generated by pricing engine."""

    __tablename__ = "quotes"

    id = Column(String(36), primary_key=True)
    exposure_id = Column(String(36), ForeignKey("exposures.id"), nullable=False, index=True)
    user_id = Column(String(36), ForeignKey("users.id"), nullable=False, index=True)
    currency_pair = Column(String(10), nullable=False, index=True)
    notional = Column(Numeric(18, 2), nullable=False)
    strike = Column(Numeric(12, 6), nullable=False)
    premium = Column(Numeric(18, 2), nullable=False)
    spot_rate = Column(Numeric(12, 6), nullable=False)
    volatility = Column(Numeric(8, 6), nullable=False)
    interest_rate_domestic = Column(Numeric(8, 6), nullable=False)
    interest_rate_foreign = Column(Numeric(8, 6), nullable=False)
    time_to_expiry_years = Column(Numeric(12, 8), nullable=False)
    option_type = Column(String(10), nullable=False)  # call, put
    status = Column(String(50), default="active", nullable=False)  # active, accepted, rejected, expired
    valid_until = Column(DateTime(timezone=True), nullable=False, index=True)
    accepted_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationships
    exposure = relationship("Exposure", back_populates="quotes")
    user = relationship("User", back_populates="quotes")
    orders = relationship("Order", back_populates="quote")

    __table_args__ = (
        Index("ix_quotes_user_status", "user_id", "status"),
        Index("ix_quotes_valid_until", "valid_until"),
    )


class Order(Base):
    """Hedge order executed via IBKR."""

    __tablename__ = "orders"

    id = Column(String(36), primary_key=True)
    quote_id = Column(String(36), ForeignKey("quotes.id"), nullable=True, index=True)
    user_id = Column(String(36), ForeignKey("users.id"), nullable=False, index=True)
    currency_pair = Column(String(10), nullable=False, index=True)
    side = Column(String(10), nullable=False)  # buy, sell
    quantity = Column(Integer, nullable=False)
    strike = Column(Numeric(12, 6), nullable=False)
    expiry = Column(DateTime(timezone=True), nullable=False)
    limit_price = Column(Numeric(18, 6))
    order_type = Column(String(20), nullable=False, default="LIMIT")  # LIMIT, MARKET
    ib_order_id = Column(Integer, index=True)
    ib_contract_id = Column(Integer)
    status = Column(String(50), default="pending", nullable=False)  # pending, submitted, filled, cancelled, rejected
    submitted_at = Column(DateTime(timezone=True))
    acknowledged_at = Column(DateTime(timezone=True))
    filled_at = Column(DateTime(timezone=True))
    average_fill_price = Column(Numeric(18, 6))
    filled_quantity = Column(Integer, default=0)
    fills = Column(JSON)  # Array of fill records
    commission = Column(Numeric(18, 2))
    rejection_reason = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationships
    quote = relationship("Quote", back_populates="orders")
    user = relationship("User", back_populates="orders")

    __table_args__ = (
        Index("ix_orders_user_status", "user_id", "status"),
        Index("ix_orders_ib_order_id", "ib_order_id"),
    )


class Payment(Base):
    """Payment transaction (collect or payout)."""

    __tablename__ = "payments"

    id = Column(String(36), primary_key=True)
    provider = Column(String(50), nullable=False, index=True)  # stripe, dlocal, wise
    payment_type = Column(String(20), nullable=False)  # collect, payout
    amount = Column(Numeric(18, 2), nullable=False)
    currency = Column(String(3), nullable=False)
    status = Column(String(50), default="pending", nullable=False)  # pending, processing, completed, failed, cancelled
    customer_meta = Column(JSON)
    beneficiary_id = Column(String(36), ForeignKey("beneficiaries.id"), nullable=True, index=True)
    checkout_link = Column(String(500))
    bank_debit_intent = Column(String(255))
    idempotency_key = Column(String(255), unique=True, index=True)
    external_reference = Column(String(255), unique=True, index=True)
    fee_amount = Column(Numeric(18, 2))
    fee_currency = Column(String(3))
    error_message = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationships
    beneficiary = relationship("Beneficiary", back_populates="payouts")
    fee_breakdown = relationship("FeeBreakdown", back_populates="payment", cascade="all, delete-orphan")

    __table_args__ = (Index("ix_payments_status_created", "status", "created_at"),)


class Beneficiary(Base):
    """Payout beneficiary information."""

    __tablename__ = "beneficiaries"

    id = Column(String(36), primary_key=True)
    currency = Column(String(3), nullable=False)
    account_holder_name = Column(String(255), nullable=False)
    account_number = Column(String(100))
    routing_number = Column(String(50))
    swift_code = Column(String(20))
    iban = Column(String(50))
    bank_name = Column(String(255))
    bank_address = Column(Text)
    beneficiary_address = Column(Text)
    meta = Column(JSON)  # Additional provider-specific fields
    idempotency_key = Column(String(255), unique=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationships
    payouts = relationship("Payment", back_populates="beneficiary")


class FeeBreakdown(Base):
    """Itemized fee breakdown for a payment."""

    __tablename__ = "fee_breakdown"

    id = Column(String(36), primary_key=True)
    payment_id = Column(String(36), ForeignKey("payments.id"), nullable=False, index=True)
    description = Column(String(255), nullable=False)
    amount = Column(Numeric(18, 2), nullable=False)
    currency = Column(String(3), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    payment = relationship("Payment", back_populates="fee_breakdown")


class AuditLog(Base):
    """Tamper-evident audit log with hash-chain integrity."""

    __tablename__ = "audit_logs"

    id = Column(String(36), primary_key=True)
    sequence_number = Column(Integer, nullable=False, unique=True, index=True)
    timestamp = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)
    actor = Column(String(255), nullable=False)  # User ID or system identifier
    action = Column(String(100), nullable=False, index=True)  # CREATE_QUOTE, SUBMIT_ORDER, etc.
    resource_type = Column(String(50), nullable=False)  # quote, order, payment, etc.
    resource_id = Column(String(36), nullable=False, index=True)
    payload = Column(JSON, nullable=False)  # Complete record of the action
    previous_hash = Column(String(64), nullable=False)  # SHA-256 of previous log entry
    current_hash = Column(String(64), nullable=False, unique=True)  # SHA-256 of this entry
    ip_address = Column(String(45))  # IPv4 or IPv6
    user_agent = Column(String(500))

    __table_args__ = (
        Index("ix_audit_actor_action", "actor", "action"),
        Index("ix_audit_resource", "resource_type", "resource_id"),
    )


class MarketDataSnapshot(Base):
    """Market data snapshots for pricing and analytics."""

    __tablename__ = "market_data_snapshots"

    id = Column(String(36), primary_key=True)
    currency_pair = Column(String(10), nullable=False, index=True)
    spot_rate = Column(Numeric(12, 6), nullable=False)
    bid = Column(Numeric(12, 6))
    ask = Column(Numeric(12, 6))
    implied_volatility = Column(Numeric(8, 6))
    tenor = Column(String(10))  # 1M, 3M, 6M, 1Y
    interest_rate_domestic = Column(Numeric(8, 6))
    interest_rate_foreign = Column(Numeric(8, 6))
    source = Column(String(50), nullable=False)  # banxico, bloomberg, manual
    timestamp = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)
    is_stale = Column(Boolean, default=False, nullable=False)
    extra_data = Column(JSON)

    __table_args__ = (
        Index("ix_market_data_pair_timestamp", "currency_pair", "timestamp"),
        Index("ix_market_data_stale", "is_stale", "timestamp"),
    )
